### ISSUE TITLE
More default CModels

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_oai_download_link#1]
Since it's [such a hassle](https://jira.duraspace.org/browse/ISLANDORA-2013) to look up the precise names of each CModel, it would be good to include a default download datastream for each of the more commonly-used CModels as a starting point. 

Here's a sample list from my config:

> islandora:sp_basic_image = OBJ
> islandora:sp_large_image_cmodel = JP2
> ir:thesisCModel = PDF
> ir:citationCModel = PDF
> islandora:bookCModel = PDF
> islandora:newspaperIssueCModel = PDF
> islandora:sp_pdf = OBJ
> islandora:sp_videoCModel = MP4

**Comment by mjordan** [comment]
OK, thanks, I'll add those as defaults.

**Comment by mjordan** [comment]
Merged with ec17b8029a92605708b7b0663f70d0000769c993.
