### ISSUE TITLE
Weird cloning behaviour

### ISSUE THREAD

**Issue by bondjimbond** [mjordan/islandora_oai_download_link#2]
Something set up oddly? Here are the messages I get when I clone the repo (two different times - one in Vagrant and one in production site):

> Cloning into 'islandora_oai_download_link'...
> remote: Counting objects: 38, done.
> remote: Compressing objects: 100% (22/22), done.
> remote: Total 38 (delta 17), reused 32 (delta 11), pack-reused 0
> Unpacking objects: 100% (38/38), done.
> Checking connectivity... done.
> warning: remote HEAD refers to nonexistent ref, unable to checkout.
> 
> brandonw@bceln:/var/www/drupal7/sites/all/modules$ cd islandora_oai_download_link
> brandonw@bceln:/var/www/drupal7/sites/all/modules/islandora_oai_download_link$ git status
> On branch master
> 
> Initial commit
> 
> nothing to commit (create/copy files and use "git add" to track)

It starts you off in the "master" branch, although there isn't actually a branch named "master", and thus you start out detached from HEAD. Checking out 7.x gets you on track, but initial clone might cause problems for some folks.

**Comment by mjordan** [comment]
No idea. I'll investigate.

**Comment by mjordan** [comment]
OK, fixed. Even though the default branch was 7.x, Git thought it should be master. I flipped the default branches and then reset it to 7.x again and the error is now gone. If you could confirm I'd appreciate it.

**Comment by bondjimbond** [comment]
Yep, seems to work. New clone creates 7.x and tracks. Though for some reason there's now a "master" branch as well.

**Comment by mjordan** [comment]
I forgot to delete master, which I've just done. Now we get what we expect:

```
[islandora_oai_download_link]$ git branch -a
* 7.x
  remotes/origin/7.x
  remotes/origin/HEAD -> origin/7.x
```
